version: "3.7"
services:
    web:
        container_name: im
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"

        # environment:
        #     - DJANGO_SETTINGS_MODULE=project/settings

        command: bash -c "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
        volumes:
          - ./:/usr/src/app
        restart: always
        tty: true
        stdin_open: true
        networks:
            - cleancode_network
networks:
  cleancode_network:
    driver: bridge