# Generated by Django 4.2 on 2023-05-31 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_porder_product_supplier_porderdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porder',
            name='supplier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='supplier'),
        ),
    ]
