# Generated by Django 4.2.1 on 2023-06-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_porder_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='porder',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='is ordered'),
        ),
    ]
