# Generated by Django 4.2 on 2023-06-02 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_porder_is_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('porder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.porder', verbose_name='purchare order')),
            ],
        ),
        migrations.CreateModel(
            name='GRNDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='quantity')),
                ('is_ordered', models.BooleanField(blank=True, null=True, verbose_name='is ordered')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grn', verbose_name='grn')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='product')),
            ],
        ),
    ]
