# Generated by Django 4.2 on 2023-06-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_grn_grndetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grndetail',
            name='is_ordered',
        ),
        migrations.AddField(
            model_name='grndetail',
            name='is_done',
            field=models.BooleanField(blank=True, null=True, verbose_name='is done'),
        ),
    ]
