# Generated by Django 4.2.1 on 2023-06-03 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_grndetail_is_ordered_grndetail_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='account'),
        ),
    ]
