# Generated by Django 4.2.1 on 2023-06-03 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_grn_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grn',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='porder',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='grn',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='account'),
        ),
    ]
