# Generated by Django 4.2.1 on 2023-06-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_grn_options_alter_porder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=100, verbose_name='gender')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='phone')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='age')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('birthday', models.DateField(blank=True, max_length=10, null=True, verbose_name='birthday')),
                ('type', models.CharField(blank=True, default='Normal', max_length=50, null=True, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='SOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255, verbose_name='status')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='quantity')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='price')),
                ('porder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sorder', verbose_name='sale order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='product')),
            ],
        ),
    ]
