# Generated by Django 4.2.1 on 2023-06-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customer_sorder_sorderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sorderdetail',
            old_name='porder',
            new_name='sorder',
        ),
    ]
