# Generated by Django 4.2.1 on 2023-06-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_porder_sorderdetail_sorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorderdetail',
            name='price',
        ),
    ]
