# Generated by Django 4.2.1 on 2023-06-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_grndetail_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grndetail',
            name='is_done',
        ),
        migrations.AddField(
            model_name='grndetail',
            name='is_expiry',
            field=models.BooleanField(blank=True, null=True, verbose_name='is expiry'),
        ),
    ]
