# Generated by Django 4.2.1 on 2023-06-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_grndetail_is_done_grndetail_is_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorder',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='discount'),
        ),
    ]
