# Generated by Django 4.2.1 on 2023-06-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sorder_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorder',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
