# Generated by Django 4.2 on 2023-06-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_sorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_price',
            field=models.IntegerField(default=0, verbose_name='bulk_price'),
            preserve_default=False,
        ),
    ]
