# Generated by Django 4.2.1 on 2023-06-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_product_bulk_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Membership', 'Membership'), ('Wholesale Customer', 'Wholesale Customer')], default='Normal', max_length=50, null=True, verbose_name='type'),
        ),
    ]
