# Generated by Django 4.2 on 2023-06-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bulk_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='bulk_price'),
        ),
    ]
